# Generated by Django 3.1 on 2020-10-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaToWorkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='area_to_work',
            field=models.ManyToManyField(blank=True, to='users.AreaToWorkModel', verbose_name='area_to_work'),
        ),
    ]
