# Generated by Django 3.1 on 2020-09-25 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_dbs_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalListModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hospital', models.CharField(max_length=100)),
            ],
        ),
    ]
