# Generated by Django 3.1 on 2020-09-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_hospitals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hospitals',
            field=models.ManyToManyField(blank=True, to='users.HospitalListModel', verbose_name='hospital'),
        ),
    ]
