# Generated by Django 3.1 on 2020-09-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='avilibility',
            field=models.CharField(choices=[('Avilible', 'Avilible'), ('Busy', 'Busy')], max_length=10),
        ),
    ]
