# Generated by Django 3.1 on 2020-10-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hospital',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
