# Generated by Django 3.1 on 2020-10-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_event_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='area',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
