# Generated by Django 3.1 on 2020-10-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201011_1458'),
        ('shifts', '0002_auto_20200930_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.areatoworkmodel'),
        ),
    ]
