hospitallist = [
    (1, 'London - Atkinson Morley Hospital'),
    (2, 'London - Banstead Hospital'),
    (3, 'London - Barnes Hospital, London'),
    (4, 'London - Barnet Hospital'),
    (5, 'London - Bethlem Royal Hospital'),
    (6, 'London - Bexley Hospital'),
    (7, 'London - Bexley Hospital, Bexleyheath'),
    (8, 'London - Bromley Hospital'),
    (9, 'London - Cassel Hospital'),
    (10, 'London - Central Middlesex Hospital'),
    (11, 'London - Charing Cross Hospital'),
    (12, 'London - Chase Farm Hospital'),
    (13, 'London - Chelsea and Westminster Hospital'),
    (14, 'London - Claybury Hospital'),
    (15, 'London - Croydon University Hospital'),
    (16, 'London - Dulwich Community Hospital'),
    (17, 'London - Ealing Hospital'),
    (18, 'London - Eastman Dental Hospital'),
    (19, 'London - Erith and District Hospital'),
    (20, 'London - Evelina London Children\'s Hospital'),
    (21, 'London - ExCeL London'),
    (22, 'London - Finchley Memorial Hospital'),
    (23, 'London - Friern Hospital'),
    (24, 'London - Fulham Hospital'),
    (25, 'London - General Lying-In Hospital'),
    (26, 'London - Goodmayes Hospital'),
    (27, 'London - Great Ormond Street Hospital'),
    (28, 'London - Greenwich District Hospital'),
    (29, 'London - Guy\'s Hospital'),
    (30, 'London - Hammersmith Hospital'),
    (31, 'London - Harefield Hospital'),
    (32, 'London - Harold Wood Hospital'),
    (33, 'London - University College Hospital at Westmoreland Street'),
    (34, 'London - Hillingdon Hospital'),
    (35, 'London - Homerton University Hospital'),
    (36, 'London - Hospital for Tropical Diseases'),
    (37, 'London - King George Hospital, London'),
    (38, 'London - King\'s College Hospital'),
    (39, 'London - Kingston Hospital'),
    (40, 'London - Lambeth Hospital'),
    (41, 'London - London Lock Hospital'),
    (42, 'London - Maudsley Hospital'),
    (43, 'London - Memorial Hospital, Woolwich'),
    (44, 'London - Metropolitan Free Hospital'),
    (45, 'London - Michael Rutter Centre for Children and Adolescents'),
    (46, 'London - Middlesex Hospital'),
    (47, 'London - Mile End Hospital'),
    (48, 'London - Miller General Hospital'),
    (49, 'London - Moorfields Eye Hospital'),
    (50, 'London - Mount Vernon Hospital'),
    (51, 'London - National Hospital for Neurology and Neurosurgery'),
    (52, 'London - NHS Nightingale Hospital London'),
    (53, 'London - North Middlesex University Hospital'),
    (54, 'London - Northwick Park Hospital'),
    (55, 'London - Oldchurch Hospital'),
    (56, 'London - Princess Royal University Hospital'),
    (57, 'London - Queen Charlotte\'s and Chelsea Hospital'),
    (58, 'London - Queen Elizabeth Hospital for Children'),
    (59, 'London - Queen Elizabeth Hospital, London'),
    (60, 'London - Queen Mary\'s Hospital, Roehampton'),
    (61, 'London - Queen Mary\'s Hospital, Sidcup'),
    (62, 'London - Queen\'s Hospital'),
    (63, 'London - Richmond Royal Hospital'),
    (64, 'London - Royal Brompton Hospital'),
    (65, 'London - Royal Free Hospital'),
    (66, 'London - Royal London Hospital'),
    (67, 'London - Royal London Hospital for Integrated Medicine'),
    (68, 'London - Royal Marsden Hospital'),
    (69, 'London - Royal National Orthopaedic Hospital'),
    (70, 'London - Royal National Throat, Nose and Ear Hospital'),
    (71, 'London - Rush Green Hospital'),
    (72, 'London - St Ann\'s Hospital'),
    (73, 'London - St George\'s Hospital'),
    (74, 'London - St George\'s Hospital, Havering'),
    (75, 'London - St Helier Hospital'),
    (76, 'London - St Mark\'s Hospital'),
    (77, 'London - St Mary\'s Hospital, London'),
    (78, 'London - St Pancras Hospital'),
    (79, 'London - St Thomas\' Hospital'),
    (80, 'London - Springfield University Hospital'),
    (81, 'London - St Alfege\'s Hospital'),
    (82, 'London - St Bartholomew\'s Hospital'),
    (83, 'London - St Bernard\'s Hospital, Hanwell'),
    (84, 'London - St Charles\' Hospital'),
    (85, 'London - St James\' Hospital, Balham'),
    (86, 'London - Teddington Memorial Hospital'),
    (87, 'London - The Gordon Hospital'),
    (88, 'London - Tolworth Hospital'),
    (89, 'London - UCH Macmillan Cancer Centre'),
    (90, 'London - University College Hospital'),
    (91, 'London - University Hospital Lewisham'),
    (92, 'London - West Middlesex University Hospital'),
    (93, 'London - Western Eye Hospital'),
    (94, 'London - Whipps Cross University Hospital'),
    (95, 'London - Whittington Hospital'),
    (96, 'London - Wilson Hospital'),

]
